#!/bin/bash

/usr/bin/gdbus call --session --dest org.gnome.Shell --object-path /org/gnome/Shell --method org.gnome.Shell.Eval 'Main.overview.viewSelector._showAppsButton.checked = true;
Main.overview.toggle();';